### ISSUE TITLE
add "https redirect" possibility

### ISSUE THREAD

**Issue by Koizumi85** [cloudfoundry-community/cf-haproxy-boshrelease#10]
Hello,

we have a cloudfoundry deployment using the cf-haproxy-boshrelease as load balancer. We would like to redirect all users to https, so that they are not able to use http anymore.
I think everything would be okay with adding the following line in the "http-in"-frontend:

"redirect scheme https code 301 if !{ ssl_fc }"

Would it be possible to add a configuration option for this? something like "ha_proxy.always_redirect_to_https"?

Thank you very much.

**Comment by longnguyen11288** [comment]
yes this would be possible, can you make PR with changes?

**Comment by Koizumi85** [comment]
I am not really familiar with Pull Requests, but i will try to make one. Do i have to sign some CLA or something like this before?

**Comment by longnguyen11288** [comment]
Nope!


On August 24, 2015 at 7:33:29 AM, Koizumi85 (notifications@github.com) wrote:

I am not really familiar with Pull Requests, but i will try to make one. Do i have to sign some CLA or something like this before?

**Comment by ronakbanka** [comment]
@Koizumi85 Even i was thinking to put this in , If you are opening the PR i will wait or can open one if you are fine with it?

**Comment by shinji62** [comment]
@Koizumi85 this PR is good training for you :)

**Comment by Koizumi85** [comment]
Little question... how can i test if my change in the config-template works like expected?
I am really new with this whole cloudfoundry and template stuff and have no idea :D

The fix is a little bit different by the way. I noticed, that it would be not enough to simply enable the redirect for every domain and therefore i had the idea to add some property like "additional_http_configuration_options", where someone could provide an array with lines like "redirect scheme https code 301 if { hdr(Host) -i www.mobiti.de } !{ ssl_fc }" which are all lined up at the end of the "frontend http-in" block.
Is there anything stupid with this idea?

**Comment by shinji62** [comment]
You can too options : 

1- Force https for all domain
2- If 1 is false you can give an array of domain 

If 1 is false and no domain so you have nothing where you need to force the redirect.

**Comment by ronakbanka** [comment]
@shinji62 @Koizumi85 Guys how about using map feature from HAproxy.
With the host array can populate a map table and check hdr(host) against the map. Will be much faster in case of large number of hosts, as map uses tree for search instead of looking each entry in frontend .

http://blog.haproxy.com/2015/01/26/web-application-name-to-backend-mapping-in-haproxy/

**Comment by shinji62** [comment]
We should not go deeper than the domain level and keep the wildcard.
Normally you don't need to force redirect to 1000 of domain.
We can use the map feature but again we should only use the dmain level

mydomain.com
yourdomain.com


and not app1.domain.com and so on..

**Comment by Koizumi85** [comment]
@shinji62 @ronakbanka 
Hello,
first thanks for your ideas. Not sure if i will get this done, but i will try it out. 
But again my question from above: How can i test if my templates are working as expected? Is there a method to process the templates with a given set of properties and to look at the output?
I did never build a cloudfoundry job, so i don't have a clue what to do :-D

**Comment by shinji62** [comment]
From my side I am just using bosh-lite and try to deploy my bosh release locally and just go inside the Vm after that.

**Comment by Koizumi85** [comment]
Okay, then i will try to resolve this issue. If i have problems with that i will contact you again :-)

**Comment by Koizumi85** [comment]
@shinji62 Hi, currently I am trying to get the cf-haproxy-boshrelease running on bosh-lite, but am not successful.
I installed vagrant in the recommended version and virtualbox also. bosh-lite is starting and after targetting the director i tried to use:
templates/make_manifest warden 10.244.0.22 from repository root directory. But at the moment the script tries to upload a stemcell (because there isn't one installed) and does not find one.
I think the problem occurs, because the script tries to find the URL with the following command:

bosh public stemcells --full | grep cpi | grep ubuntu | sort -nr | head -n1 | awk '{ print $4 }'

But instead of "cpi" it should be "warden", right? the cpi comes from the "bosh status" command which returns:

Director
  Name       Bosh Lite Director
  URL        https://192.168.50.4:25555
  Version    1.3071.0 (00000000)
  User       admin
  UUID       56a8b33a-ed1a-4918-822f-a4266e659af1
  CPI        cpi
  dns        disabled
  compiled_package_cache enabled (provider: local)
  snapshots  disabled

Is this a change in the behaviour of bosh-lite or am I doing something wrong in setting up bosh-lite? If the behaviour of bosh-lite did change it should be reflected by the make_manifest script and the documentation.

**Comment by Koizumi85** [comment]
Okay, I think I have a solution which works and will try to explain (don't make PR now, because i have to clean up a little bit):

I introduced two properties: "https_redirect_all" (boolean) and "https_redirect_domains" (String Array)
- If https_redirect_all is true, all requests will be redirected
- If https_redirect_all is false, I am inserting the following two lines: 
```
acl ssl_redirect hdr(host),lower,map_end(/var/vcap/jobs/haproxy/config/ssl_redirect.map,false) -m str true
redirect scheme https code 301 if ssl_redirect
```
In these two lines the following happens
- extract the Host-Header from request
- lower-case the host
- lookup the map in "ssl_redirect.map" for entries ENDING with [HOST] and return "false" if not found
- proof if result from map equals the string "true"
- if yes make the https redirect

The map-file is build like following:
```
mydomain.com          true
yourdomain.com        true
anotherdomain.com   true
```

This should work, right? I've done some tests and it seems okay for now. Like said before i will clean up my coding the next days and make the PR then.

Grreetings

**Comment by shinji62** [comment]
Should be ok, waiting for your PR too

**Comment by Koizumi85** [comment]
@shinji62 Created PR for this also. See PR #15

**Comment by geofffranks** [comment]
:+1: looks good to me, @shinji62, can you review as well?

**Comment by shinji62** [comment]
@geofffranks LGTM :)

**Comment by geofffranks** [comment]
Merged, and part of the v6 release
