### ISSUE TITLE
Compile with USE_ZLIB=yes and provide configuration options in haproxy.config.erb

### ISSUE THREAD

**Issue by Koizumi85** [cloudfoundry-community/cf-haproxy-boshrelease#11]
For the possibility of using gzip compression, the release should be compiled with USE_ZLIB=yes and there should be configuration properties for enabling gzip compression like the following:

compression algo gzip
compression type text/html text/plain text/css

I think best would be to provide a parameter for defining the "text/html text/plain text/css" part. If the parameter is not empty, both lines should be set with the content of the parameter in second line.

Good idea?

**Comment by Koizumi85** [comment]
I worked on this issue today and it seems that I fixed it. I will provide a PR the next days after some cleanups.

While working on this I found a wrong configuration i believe.
In the file packages/packaging the version of haproxy-tarball was "1.5.14"
In the file packages/spec the version for haproxy was "1.5.10" which lead to a "missing file" error while compiling the package.
I fixed it so that in packages/spec the version is also 1.5.14 now. This is okay, isn't it?

**Comment by shinji62** [comment]
Thanks please a PR.

**Comment by Koizumi85** [comment]
@shinji62 Hi, created the PR (Hope i did it right. Never did this before :) )
See PR #14

**Comment by geofffranks** [comment]
:+1: from me, @shinji62?

**Comment by shinji62** [comment]
LGTM

**Comment by geofffranks** [comment]
Merged, and released in v6. Sorry for the delays!

**Comment by Koizumi85** [comment]
Thank you. Good timing. Tomorrow i will make some maintanance and will update to the new version then :+1:
