### ISSUE TITLE
Add app_ssh_access to provide ssh access to containers

### ISSUE THREAD

**Issue by ramelito** [cloudfoundry-community/cf-haproxy-boshrelease#12]
cc.allow_app_ssh_access:
    default: true
    description: "Allow users to change the value of the app-level allow_ssh attribute"

  app_ssh.port:
    description: "External port for SSH access to application instances"
    default: 2222

**Comment by longnguyen11288** [comment]
can you make PR for this?

**Comment by ramelito** [comment]
nope, it is a proposal to incorporate ssh_access to haproxy

**Comment by cromega** [comment]
@ramelito: feel free to join the discussion here: https://github.com/cloudfoundry-community/cf-haproxy-boshrelease/pull/13
