### ISSUE TITLE
Release tarball

### ISSUE THREAD

**Issue by shinji62** [cloudfoundry-community/cf-haproxy-boshrelease#6]
Any chance to have the release tarball somewhere  ?

``` bosh create release --with-tarball ```

**Comment by geofffranks** [comment]
You should be able to grab it from http://bosh.io/releases/github.com/cloudfoundry-community/cf-haproxy-boshrelease (or more specifically http://bosh.io/d/github.com/cloudfoundry-community/cf-haproxy-boshrelease). Will that work for you?

**Comment by shinji62** [comment]
Lol Did not check the bosh website sorry :)
Thanks
